name: 'devcontainer eval'
description: 'action to eval command inside devcontainer'
branding:
  icon: 'package'
  color: 'purple'
inputs:
  cmd:
    description: 'command string to eval'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cmd }}
