/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    chassis: THREE.Mesh;
    bearing: THREE.Mesh;
    low_shovel: THREE.Mesh;
    shovel_attachment: THREE.Mesh;
    engine_base: THREE.Mesh;
    exhaust: THREE.Mesh;
    exhaust001: THREE.Mesh;
    cabin: THREE.Mesh;
    tracks: THREE.Mesh;
    static_track039: THREE.Mesh;
    static_track040: THREE.Mesh;
    static_track041: THREE.Mesh;
    static_track042: THREE.Mesh;
    static_track043: THREE.Mesh;
    static_track044: THREE.Mesh;
    static_track045: THREE.Mesh;
    static_track046: THREE.Mesh;
    static_track047: THREE.Mesh;
    static_track048: THREE.Mesh;
    static_track049: THREE.Mesh;
    static_track050: THREE.Mesh;
    static_track051: THREE.Mesh;
    static_track052: THREE.Mesh;
    static_track053: THREE.Mesh;
    static_track054: THREE.Mesh;
    static_track055: THREE.Mesh;
    static_track056: THREE.Mesh;
    static_track057: THREE.Mesh;
    static_track058: THREE.Mesh;
    static_track059: THREE.Mesh;
    static_track060: THREE.Mesh;
    static_track061: THREE.Mesh;
    static_track062: THREE.Mesh;
    static_track063: THREE.Mesh;
    static_track064: THREE.Mesh;
    static_track065: THREE.Mesh;
    static_track066: THREE.Mesh;
    static_track067: THREE.Mesh;
    static_track068: THREE.Mesh;
    static_track069: THREE.Mesh;
    static_track070: THREE.Mesh;
    static_track071: THREE.Mesh;
    static_track072: THREE.Mesh;
    static_track073: THREE.Mesh;
    static_track074: THREE.Mesh;
    static_track075: THREE.Mesh;
    tracks001: THREE.Mesh;
    static_track002: THREE.Mesh;
    static_track003: THREE.Mesh;
    static_track004: THREE.Mesh;
    static_track005: THREE.Mesh;
    static_track006: THREE.Mesh;
    static_track007: THREE.Mesh;
    static_track008: THREE.Mesh;
    static_track009: THREE.Mesh;
    static_track010: THREE.Mesh;
    static_track011: THREE.Mesh;
    static_track012: THREE.Mesh;
    static_track013: THREE.Mesh;
    static_track014: THREE.Mesh;
    static_track015: THREE.Mesh;
    static_track016: THREE.Mesh;
    static_track017: THREE.Mesh;
    static_track018: THREE.Mesh;
    static_track019: THREE.Mesh;
    static_track020: THREE.Mesh;
    static_track021: THREE.Mesh;
    static_track022: THREE.Mesh;
    static_track023: THREE.Mesh;
    static_track024: THREE.Mesh;
    static_track025: THREE.Mesh;
    static_track026: THREE.Mesh;
    static_track027: THREE.Mesh;
    static_track028: THREE.Mesh;
    static_track029: THREE.Mesh;
    static_track030: THREE.Mesh;
    static_track031: THREE.Mesh;
    static_track032: THREE.Mesh;
    static_track033: THREE.Mesh;
    static_track034: THREE.Mesh;
    static_track035: THREE.Mesh;
    static_track036: THREE.Mesh;
    static_track037: THREE.Mesh;
    static_track038: THREE.Mesh;
    drill_profile: THREE.Mesh;
    drill_bearing: THREE.Mesh;
    drill_pivot: THREE.Mesh;
  };
  materials: {
    black_metal: THREE.MeshStandardMaterial;
    yellow_metal: THREE.MeshStandardMaterial;
    drill: THREE.MeshStandardMaterial;
  };
};

export default function Model({ ...props }: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(
    "/digger_v1_static.glb"
  ) as unknown as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.chassis.geometry}
        material={nodes.chassis.material}
        position={[0, 1.1, 0]}
      >
        <mesh
          geometry={nodes.bearing.geometry}
          material={nodes.bearing.material}
          position={[0, -0.7, 0]}
        />
      </mesh>
      <mesh
        geometry={nodes.low_shovel.geometry}
        material={nodes.low_shovel.material}
        position={[0, 0.21, -2.13]}
      >
        <mesh
          geometry={nodes.shovel_attachment.geometry}
          material={nodes.shovel_attachment.material}
          position={[0, 0.1, 0.76]}
        />
      </mesh>
      <mesh
        geometry={nodes.engine_base.geometry}
        material={materials.yellow_metal}
        position={[0, 0.8, -0.3]}
      >
        <mesh
          geometry={nodes.exhaust.geometry}
          material={nodes.exhaust.material}
          position={[0.59, 0.78, 1.44]}
          rotation={[0, 0.72, 0]}
        />
        <mesh
          geometry={nodes.exhaust001.geometry}
          material={nodes.exhaust001.material}
          position={[0.42, 0.78, 1.44]}
          rotation={[0, 0.72, 0]}
        />
      </mesh>
      <mesh
        geometry={nodes.cabin.geometry}
        material={nodes.cabin.material}
        position={[-0.53, 1.77, -0.06]}
      />
      <mesh
        geometry={nodes.tracks.geometry}
        material={nodes.tracks.material}
        position={[-0.81, 0.3, 0]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.static_track039.geometry}
        material={nodes.static_track039.material}
        position={[-0.81, 0, 1.54]}
        rotation={[3.12, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track040.geometry}
        material={nodes.static_track040.material}
        position={[-0.81, 0, 1.31]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track041.geometry}
        material={nodes.static_track041.material}
        position={[-0.81, 0, 1.08]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track042.geometry}
        material={nodes.static_track042.material}
        position={[-0.81, 0, 0.85]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track043.geometry}
        material={nodes.static_track043.material}
        position={[-0.81, 0, 0.62]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track044.geometry}
        material={nodes.static_track044.material}
        position={[-0.81, 0, 0.39]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track045.geometry}
        material={nodes.static_track045.material}
        position={[-0.81, 0, 0.16]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track046.geometry}
        material={nodes.static_track046.material}
        position={[-0.81, 0, -0.07]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track047.geometry}
        material={nodes.static_track047.material}
        position={[-0.81, 0, -0.31]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track048.geometry}
        material={nodes.static_track048.material}
        position={[-0.81, 0, -0.54]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track049.geometry}
        material={nodes.static_track049.material}
        position={[-0.81, 0, -0.77]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track050.geometry}
        material={nodes.static_track050.material}
        position={[-0.81, 0, -1]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track051.geometry}
        material={nodes.static_track051.material}
        position={[-0.81, 0, -1.23]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track052.geometry}
        material={nodes.static_track052.material}
        position={[-0.81, 0, -1.46]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track053.geometry}
        material={nodes.static_track053.material}
        position={[-0.81, 0.02, -1.69]}
        rotation={[-2.96, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track054.geometry}
        material={nodes.static_track054.material}
        position={[-0.81, 0.12, -1.88]}
        rotation={[-2.33, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track055.geometry}
        material={nodes.static_track055.material}
        position={[-0.81, 0.31, -1.95]}
        rotation={[-1.51, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track056.geometry}
        material={nodes.static_track056.material}
        position={[-0.81, 0.5, -1.86]}
        rotation={[-0.69, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track057.geometry}
        material={nodes.static_track057.material}
        position={[-0.81, 0.58, -1.66]}
        rotation={[-0.13, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track058.geometry}
        material={nodes.static_track058.material}
        position={[-0.81, 0.6, -1.43]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track059.geometry}
        material={nodes.static_track059.material}
        position={[-0.81, 0.6, -1.2]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track060.geometry}
        material={nodes.static_track060.material}
        position={[-0.81, 0.6, -0.97]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track061.geometry}
        material={nodes.static_track061.material}
        position={[-0.81, 0.6, -0.73]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track062.geometry}
        material={nodes.static_track062.material}
        position={[-0.81, 0.6, -0.5]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track063.geometry}
        material={nodes.static_track063.material}
        position={[-0.81, 0.6, -0.27]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track064.geometry}
        material={nodes.static_track064.material}
        position={[-0.81, 0.6, -0.04]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track065.geometry}
        material={nodes.static_track065.material}
        position={[-0.81, 0.6, 0.19]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track066.geometry}
        material={nodes.static_track066.material}
        position={[-0.81, 0.6, 0.42]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track067.geometry}
        material={nodes.static_track067.material}
        position={[-0.81, 0.6, 0.65]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track068.geometry}
        material={nodes.static_track068.material}
        position={[-0.81, 0.6, 0.88]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track069.geometry}
        material={nodes.static_track069.material}
        position={[-0.81, 0.6, 1.11]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track070.geometry}
        material={nodes.static_track070.material}
        position={[-0.81, 0.6, 1.34]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track071.geometry}
        material={nodes.static_track071.material}
        position={[-0.81, 0.6, 1.57]}
        rotation={[0.04, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track072.geometry}
        material={nodes.static_track072.material}
        position={[-0.81, 0.54, 1.79]}
        rotation={[0.44, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track073.geometry}
        material={nodes.static_track073.material}
        position={[-0.81, 0.39, 1.93]}
        rotation={[1.2, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track074.geometry}
        material={nodes.static_track074.material}
        position={[-0.81, 0.19, 1.92]}
        rotation={[2.04, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track075.geometry}
        material={nodes.static_track075.material}
        position={[-0.81, 0.05, 1.77]}
        rotation={[2.78, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.tracks001.geometry}
        material={nodes.tracks001.material}
        position={[0.82, 0.3, 0]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.static_track002.geometry}
        material={nodes.static_track002.material}
        position={[0.82, 0, 1.54]}
        rotation={[3.12, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track003.geometry}
        material={nodes.static_track003.material}
        position={[0.82, 0, 1.31]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track004.geometry}
        material={nodes.static_track004.material}
        position={[0.82, 0, 1.08]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track005.geometry}
        material={nodes.static_track005.material}
        position={[0.82, 0, 0.85]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track006.geometry}
        material={nodes.static_track006.material}
        position={[0.82, 0, 0.62]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track007.geometry}
        material={nodes.static_track007.material}
        position={[0.82, 0, 0.39]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track008.geometry}
        material={nodes.static_track008.material}
        position={[0.82, 0, 0.16]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track009.geometry}
        material={nodes.static_track009.material}
        position={[0.82, 0, -0.07]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track010.geometry}
        material={nodes.static_track010.material}
        position={[0.82, 0, -0.31]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track011.geometry}
        material={nodes.static_track011.material}
        position={[0.82, 0, -0.54]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track012.geometry}
        material={nodes.static_track012.material}
        position={[0.82, 0, -0.77]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track013.geometry}
        material={nodes.static_track013.material}
        position={[0.82, 0, -1]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track014.geometry}
        material={nodes.static_track014.material}
        position={[0.82, 0, -1.23]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track015.geometry}
        material={nodes.static_track015.material}
        position={[0.82, 0, -1.46]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track016.geometry}
        material={nodes.static_track016.material}
        position={[0.82, 0.02, -1.69]}
        rotation={[-2.96, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track017.geometry}
        material={nodes.static_track017.material}
        position={[0.82, 0.12, -1.88]}
        rotation={[-2.33, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track018.geometry}
        material={nodes.static_track018.material}
        position={[0.82, 0.31, -1.95]}
        rotation={[-1.51, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track019.geometry}
        material={nodes.static_track019.material}
        position={[0.82, 0.5, -1.86]}
        rotation={[-0.69, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track020.geometry}
        material={nodes.static_track020.material}
        position={[0.82, 0.58, -1.66]}
        rotation={[-0.13, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track021.geometry}
        material={nodes.static_track021.material}
        position={[0.82, 0.6, -1.43]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track022.geometry}
        material={nodes.static_track022.material}
        position={[0.82, 0.6, -1.2]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track023.geometry}
        material={nodes.static_track023.material}
        position={[0.82, 0.6, -0.97]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track024.geometry}
        material={nodes.static_track024.material}
        position={[0.82, 0.6, -0.73]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track025.geometry}
        material={nodes.static_track025.material}
        position={[0.82, 0.6, -0.5]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track026.geometry}
        material={nodes.static_track026.material}
        position={[0.82, 0.6, -0.27]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track027.geometry}
        material={nodes.static_track027.material}
        position={[0.82, 0.6, -0.04]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track028.geometry}
        material={nodes.static_track028.material}
        position={[0.82, 0.6, 0.19]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track029.geometry}
        material={nodes.static_track029.material}
        position={[0.82, 0.6, 0.42]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track030.geometry}
        material={nodes.static_track030.material}
        position={[0.82, 0.6, 0.65]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track031.geometry}
        material={nodes.static_track031.material}
        position={[0.82, 0.6, 0.88]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track032.geometry}
        material={nodes.static_track032.material}
        position={[0.82, 0.6, 1.11]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track033.geometry}
        material={nodes.static_track033.material}
        position={[0.82, 0.6, 1.34]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track034.geometry}
        material={nodes.static_track034.material}
        position={[0.82, 0.6, 1.57]}
        rotation={[0.04, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track035.geometry}
        material={nodes.static_track035.material}
        position={[0.82, 0.54, 1.79]}
        rotation={[0.44, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track036.geometry}
        material={nodes.static_track036.material}
        position={[0.82, 0.39, 1.93]}
        rotation={[1.2, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.static_track037.geometry}
        material={nodes.static_track037.material}
        position={[0.82, 0.19, 1.92]}
        rotation={[2.04, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.static_track038.geometry}
        material={nodes.static_track038.material}
        position={[0.82, 0.05, 1.77]}
        rotation={[2.78, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.drill_profile.geometry}
        material={materials.drill}
        position={[0, 1.09, -3.5]}
      />
      <mesh
        geometry={nodes.drill_bearing.geometry}
        material={nodes.drill_bearing.material}
        position={[0, 1.1, -1.6]}
      />
      <mesh
        geometry={nodes.drill_pivot.geometry}
        material={nodes.drill_pivot.material}
        position={[0, 1.1, -1.6]}
        rotation={[0, 0, -Math.PI / 2]}
      />
    </group>
  );
}

useGLTF.preload("/digger_v1_static.glb");
