name: build

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      PAGES_DOMAIN: erosion.thomasjamesgale.com
      BUILD_DIR: apps/web/out

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"

      - name: resolve dependencies
        run: yarn

      - name: build
        run: yarn build
