on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: build corrade resource compiler
        uses: ./.github/actions/devcontainer-eval
        with:
          cmd: "./scripts/build-corrade-rc.sh"

      - name: build engine
        uses: ./.github/actions/devcontainer-eval
        with:
          cmd: "source /home/vscode/emsdk/emsdk_env.sh && ./scripts/build-engine.sh Release"

      - name: setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"

      - name: resolve dependencies
        run: yarn

      - name: build
        run: yarn build:ci

      - name: vercel deploy
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
