name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      NEXT_PUBLIC_BASE_PATH: /erosion
      PAGES_DOMAIN: erosion.thomasjamesgale.com
      BUILD_DIR: out

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: build corrade resource compiler
        uses: ./.github/actions/devcontainer-eval
        with:
          cmd: "./scripts/build-corrade-rc.sh"

      - name: build engine
        uses: ./.github/actions/devcontainer-eval
        with:
          cmd: "source /home/vscode/emsdk/emsdk_env.sh && ./scripts/build-engine.sh Release"

      - name: setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"

      - name: resolve dependencies
        run: yarn

      - name: build
        run: yarn build:ci

      - name: configure the cname for github pages
        run: echo ${{ env.PAGES_DOMAIN }} > ${{ env.BUILD_DIR }}/CNAME

      - name: deploy github pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: ${{ env.BUILD_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
