name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      PAGES_DOMAIN: erosion.thomasjamesgale.com
      BUILD_DIR: out

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"

      - name: resolve dependencies
        run: yarn

      - name: run turbo build
        run: echo TODO

      # - name: build and export static
      #   run: yarn export

      # - name: configure the cname for github pages
      #   run: echo ${{ env.PAGES_DOMAIN }} > ${{ env.BUILD_DIR }}/CNAME

      # - name: disable jekyll
      #   run: touch ${{ env.BUILD_DIR }}/.nojekyll

      # - name: deploy github pages
      #   uses: crazy-max/ghaction-github-pages@v2.5.0
      #   with:
      #     build_dir: ${{ env.BUILD_DIR }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
