on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
            submodules: recursive

      - name: build corrade resource compiler
        uses: ./.github/actions/devcontainer-eval
        with:
          cmd: "./scripts/build-corrade-rc.sh"

      - name: build engine
        uses: ./.github/actions/devcontainer-eval
        with:
          cmd: "source /home/vscode/emsdk/emsdk_env.sh && ./scripts/build-engine.sh"

      - name: setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"

      - name: setup kernel for node testing, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a
          /etc/sysctl.conf && sudo sysctl -p

      - name: resolve dependencies
        run: yarn

      #- name: Run Unit Tests with Coverage
      #  run: yarn test:ci
      #  env:
      #    CI: true

      #- name: Cypress e2e Tests
      #  uses: cypress-io/github-action@v2.3.3
      #  with:
      #    record: true
      #    start: yarn start:instrumented
      #    command-prefix: 'percy exec -- npx'
      #    wait-on: 'http://localhost:3000'
      #    wait-on-timeout: 120
      #  env:
      #      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      #      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- name: Merge Coverage Reports
      #  run: |
      #    cp jest_coverage/coverage-final.json .nyc_output/coverage-unit-tests.json
      #    yarn nyc report --reporter=lcov --report-dir=.nyc_output
      #- name: Test Coverage to Coveralls
      #  uses: coverallsapp/github-action@v1.0.1
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
      #    path-to-lcov: .nyc_output/lcov.info

      #- name: SonarCloud Report File Preparation
      #  run: |
      #    sed -i 's/\/home\/runner\/work\/bits-to-atoms\/bits-to-atoms\//\/github\/workspace\//g' .nyc_output/lcov.info
      #- name: SonarCloud Scan
      #  uses: SonarSource/sonarcloud-github-action@v1.1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: build
        run: yarn build

      #- name: Generate Release
      #  uses: cycjimmy/semantic-release-action@v2.1.3
      #  id: semantic
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}

      #- name: Update package.json if new Release Generated
      #  if: steps.semantic.outputs.new_release_published == 'true'
      #  run: |
      #    git config --global user.name ${{ secrets.GIT_USER_NAME }}
      #    git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
      #    git commit -am "package.json updated by semantic-release"
      #    git push

      - name: configure the cname for github pages
        run: echo erosion.thomasjamesgale.com > build/CNAME

      - name: deploy github pages
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
            build_dir: build
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
