name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: thomas-gale/erosion/.github/workflows/build.yml@main
    env:
      PAGES_DOMAIN: erosion.thomasjamesgale.com
      BUILD_DIR: apps/web/out

    steps:
      - name: export static build
        run: yarn export

      - name: configure the cname for github pages
        run: echo ${{ env.PAGES_DOMAIN }} > ${{ env.BUILD_DIR }}/CNAME

      - name: disable jekyll
        run: touch ${{ env.BUILD_DIR }}/.nojekyll

      - name: deploy github pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          build_dir: ${{ env.BUILD_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
