on:
  push:
    branches:
      - main

jobs:
  devcontainer:
    runs-on: ubuntu-18.04
    env:
      PACKAGE_PAT_OWNER: thomas-gale

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: compute hash of devcontainer dockerfile
        id: computehash
        run: echo "::set-output name=hash::$(git rev-parse HEAD:.devcontainer/Dockerfile)"

      - name: login to github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.PACKAGE_PAT_OWNER }}
          password: ${{ secrets.PACKAGE_PAT }}

      - name: check if registry contains devcontainer with image hash
        id: checkexists
        run: |
          echo "Checking... ${{ steps.computehash.outputs.hash }}"
          export DOCKER_CLI_EXPERIMENTAL=enabled
          if [[ "$(docker manifest inspect ghcr.io/${{ env.REPO_OWNER }}/erosion-devcontainer:${{ steps.computehash.outputs.hash }} > /dev/null; echo $?)" == "0" ]]; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi
          export DOCKER_CLI_EXPERIMENTAL=disabled

      - name: set up qemu
        uses: docker/setup-qemu-action@v1

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: build and push devcontainer base image
        if: steps.checkexists.outputs.exists == 'false'
        uses: docker/build-push-action@v2.3.0
        with:
          push: true
          context: .
          file: ./.devcontainer/Dockerfile
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/erosion-devcontainer:${{ steps.computehash.outputs.hash }}
            ghcr.io/${{ env.REPO_OWNER }}/erosion-devcontainer:latest
