on: push

jobs:
    test:
        runs-on: ubuntu-18.04
        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: devcontainer build
              uses: ./.github/actions/setup-devcontainer
              with:
                stage: 'build'

            - name: devcontainer deploy
              uses: ./.github/actions/setup-devcontainer
              with:
                stage: 'test'
