on: push

jobs:
    test:
        runs-on: ubuntu-18.04
        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: build engine
              uses: ./.github/actions/devcontainer-eval
              with:
                cmd: 'source /home/vscode/emsdk/emsdk_env.sh && ./scripts/build-engine.sh'
